export const CHANGE_TEMPO = 'CHANGE_TEMPO';
export const CHANGE_SWING = 'CHANGE_SWING';
export const PATTERN_CHANGE = 'PATTERN_CHANGE';
export const TOGGLE_PLAY = 'TOGGLE_PLAY';
export const CHANGE_ACTIVE_SOUND = 'CHANGE_ACTIVE_SOUND';
export const CHANGE_SOUND_PROPERTY = 'CHANGE_SOUND_PROPERTY';
export const CHANGE_PATTERN_MODE = 'CHANGE_PATTERN_MODE';
